alter table TESTERY_TESTACTION add constraint FK_TESTERY_TESTACTION_ON_CATEGORY foreign key (CATEGORY_ID) references TESTERY_TESTACTION_CATEGORY(ID);
create index IDX_TESTERY_TESTACTION_ON_CATEGORY on TESTERY_TESTACTION (CATEGORY_ID);
